server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://portal-db:5432/healthportal}
    username: ${DB_USER:portal}
    password: ${DB_PASS:portal}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: wm_flyway_history

portal:
  jwt:
    secret: ${JWT_SECRET:ThisIsADevelopmentSecretKeyThatMustBeAtLeast32BytesLong!}

logging:
  level:
    de.wissensmanagement: INFO
